//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scenes/Billiards/InputActions/IA_Blliards.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Gavryk.Physics.Billiard
{
    public partial class @IA_Blliards: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @IA_Blliards()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""IA_Blliards"",
    ""maps"": [
        {
            ""name"": ""ControlMaster"",
            ""id"": ""03067473-00a3-4140-baff-4db54bb2d23b"",
            ""actions"": [
                {
                    ""name"": ""Mouse ClickRight"",
                    ""type"": ""Button"",
                    ""id"": ""5b19a40b-b094-4552-b4ac-a4619ba77e72"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Keyboard SpaceBar"",
                    ""type"": ""Button"",
                    ""id"": ""fe88f501-8c10-4ed4-9cc3-d88c982a003d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2feee535-b1e8-4d6c-8774-10025b3535e1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightFlipper"",
                    ""type"": ""Button"",
                    ""id"": ""fa396c6d-8f84-4eb2-8c4d-6ebb725b4a62"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftFlipper"",
                    ""type"": ""Button"",
                    ""id"": ""903f9fbc-70fd-40e2-8e0d-1a7c49110413"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Spring_Pinball"",
                    ""type"": ""Button"",
                    ""id"": ""36753435-fca2-4be8-bd51-9130155618fc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InvokeBallGotchaAndPinball"",
                    ""type"": ""Button"",
                    ""id"": ""8ae6e903-b70a-4bc6-9223-da86734ca1a1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""869eeaa4-b09c-40d2-b01c-76c690c5cc0f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Control"",
                    ""action"": ""Mouse ClickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6797a45c-9860-435b-9b3e-3b88c060e103"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": "";Control"",
                    ""action"": ""Keyboard SpaceBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""3cfc70f8-6a7e-4f13-a69a-ca3a72355a16"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""27d31f97-0d45-482d-81ba-5ceda82e5a4a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""fef2b859-62a2-4f3a-8a3d-c4fa0fba1763"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2bcad839-0111-4ac9-b450-a9bc2e230259"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spring_Pinball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92b5e408-d0db-4ff9-a9e9-1318c411e0e5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""450b2a58-3c5b-43ed-87b3-be007d69375a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftFlipper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06668f65-d785-4884-9226-acb4e9a26956"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InvokeBallGotchaAndPinball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Control"",
            ""bindingGroup"": ""Control"",
            ""devices"": []
        },
        {
            ""name"": ""New Control Scheme"",
            ""bindingGroup"": ""New Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // ControlMaster
            m_ControlMaster = asset.FindActionMap("ControlMaster", throwIfNotFound: true);
            m_ControlMaster_MouseClickRight = m_ControlMaster.FindAction("Mouse ClickRight", throwIfNotFound: true);
            m_ControlMaster_KeyboardSpaceBar = m_ControlMaster.FindAction("Keyboard SpaceBar", throwIfNotFound: true);
            m_ControlMaster_Movement = m_ControlMaster.FindAction("Movement", throwIfNotFound: true);
            m_ControlMaster_RightFlipper = m_ControlMaster.FindAction("RightFlipper", throwIfNotFound: true);
            m_ControlMaster_LeftFlipper = m_ControlMaster.FindAction("LeftFlipper", throwIfNotFound: true);
            m_ControlMaster_Spring_Pinball = m_ControlMaster.FindAction("Spring_Pinball", throwIfNotFound: true);
            m_ControlMaster_InvokeBallGotchaAndPinball = m_ControlMaster.FindAction("InvokeBallGotchaAndPinball", throwIfNotFound: true);
        }

        ~@IA_Blliards()
        {
            UnityEngine.Debug.Assert(!m_ControlMaster.enabled, "This will cause a leak and performance issues, IA_Blliards.ControlMaster.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // ControlMaster
        private readonly InputActionMap m_ControlMaster;
        private List<IControlMasterActions> m_ControlMasterActionsCallbackInterfaces = new List<IControlMasterActions>();
        private readonly InputAction m_ControlMaster_MouseClickRight;
        private readonly InputAction m_ControlMaster_KeyboardSpaceBar;
        private readonly InputAction m_ControlMaster_Movement;
        private readonly InputAction m_ControlMaster_RightFlipper;
        private readonly InputAction m_ControlMaster_LeftFlipper;
        private readonly InputAction m_ControlMaster_Spring_Pinball;
        private readonly InputAction m_ControlMaster_InvokeBallGotchaAndPinball;
        public struct ControlMasterActions
        {
            private @IA_Blliards m_Wrapper;
            public ControlMasterActions(@IA_Blliards wrapper) { m_Wrapper = wrapper; }
            public InputAction @MouseClickRight => m_Wrapper.m_ControlMaster_MouseClickRight;
            public InputAction @KeyboardSpaceBar => m_Wrapper.m_ControlMaster_KeyboardSpaceBar;
            public InputAction @Movement => m_Wrapper.m_ControlMaster_Movement;
            public InputAction @RightFlipper => m_Wrapper.m_ControlMaster_RightFlipper;
            public InputAction @LeftFlipper => m_Wrapper.m_ControlMaster_LeftFlipper;
            public InputAction @Spring_Pinball => m_Wrapper.m_ControlMaster_Spring_Pinball;
            public InputAction @InvokeBallGotchaAndPinball => m_Wrapper.m_ControlMaster_InvokeBallGotchaAndPinball;
            public InputActionMap Get() { return m_Wrapper.m_ControlMaster; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ControlMasterActions set) { return set.Get(); }
            public void AddCallbacks(IControlMasterActions instance)
            {
                if (instance == null || m_Wrapper.m_ControlMasterActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ControlMasterActionsCallbackInterfaces.Add(instance);
                @MouseClickRight.started += instance.OnMouseClickRight;
                @MouseClickRight.performed += instance.OnMouseClickRight;
                @MouseClickRight.canceled += instance.OnMouseClickRight;
                @KeyboardSpaceBar.started += instance.OnKeyboardSpaceBar;
                @KeyboardSpaceBar.performed += instance.OnKeyboardSpaceBar;
                @KeyboardSpaceBar.canceled += instance.OnKeyboardSpaceBar;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @RightFlipper.started += instance.OnRightFlipper;
                @RightFlipper.performed += instance.OnRightFlipper;
                @RightFlipper.canceled += instance.OnRightFlipper;
                @LeftFlipper.started += instance.OnLeftFlipper;
                @LeftFlipper.performed += instance.OnLeftFlipper;
                @LeftFlipper.canceled += instance.OnLeftFlipper;
                @Spring_Pinball.started += instance.OnSpring_Pinball;
                @Spring_Pinball.performed += instance.OnSpring_Pinball;
                @Spring_Pinball.canceled += instance.OnSpring_Pinball;
                @InvokeBallGotchaAndPinball.started += instance.OnInvokeBallGotchaAndPinball;
                @InvokeBallGotchaAndPinball.performed += instance.OnInvokeBallGotchaAndPinball;
                @InvokeBallGotchaAndPinball.canceled += instance.OnInvokeBallGotchaAndPinball;
            }

            private void UnregisterCallbacks(IControlMasterActions instance)
            {
                @MouseClickRight.started -= instance.OnMouseClickRight;
                @MouseClickRight.performed -= instance.OnMouseClickRight;
                @MouseClickRight.canceled -= instance.OnMouseClickRight;
                @KeyboardSpaceBar.started -= instance.OnKeyboardSpaceBar;
                @KeyboardSpaceBar.performed -= instance.OnKeyboardSpaceBar;
                @KeyboardSpaceBar.canceled -= instance.OnKeyboardSpaceBar;
                @Movement.started -= instance.OnMovement;
                @Movement.performed -= instance.OnMovement;
                @Movement.canceled -= instance.OnMovement;
                @RightFlipper.started -= instance.OnRightFlipper;
                @RightFlipper.performed -= instance.OnRightFlipper;
                @RightFlipper.canceled -= instance.OnRightFlipper;
                @LeftFlipper.started -= instance.OnLeftFlipper;
                @LeftFlipper.performed -= instance.OnLeftFlipper;
                @LeftFlipper.canceled -= instance.OnLeftFlipper;
                @Spring_Pinball.started -= instance.OnSpring_Pinball;
                @Spring_Pinball.performed -= instance.OnSpring_Pinball;
                @Spring_Pinball.canceled -= instance.OnSpring_Pinball;
                @InvokeBallGotchaAndPinball.started -= instance.OnInvokeBallGotchaAndPinball;
                @InvokeBallGotchaAndPinball.performed -= instance.OnInvokeBallGotchaAndPinball;
                @InvokeBallGotchaAndPinball.canceled -= instance.OnInvokeBallGotchaAndPinball;
            }

            public void RemoveCallbacks(IControlMasterActions instance)
            {
                if (m_Wrapper.m_ControlMasterActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IControlMasterActions instance)
            {
                foreach (var item in m_Wrapper.m_ControlMasterActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ControlMasterActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public ControlMasterActions @ControlMaster => new ControlMasterActions(this);
        private int m_ControlSchemeIndex = -1;
        public InputControlScheme ControlScheme
        {
            get
            {
                if (m_ControlSchemeIndex == -1) m_ControlSchemeIndex = asset.FindControlSchemeIndex("Control");
                return asset.controlSchemes[m_ControlSchemeIndex];
            }
        }
        private int m_NewControlSchemeSchemeIndex = -1;
        public InputControlScheme NewControlSchemeScheme
        {
            get
            {
                if (m_NewControlSchemeSchemeIndex == -1) m_NewControlSchemeSchemeIndex = asset.FindControlSchemeIndex("New Control Scheme");
                return asset.controlSchemes[m_NewControlSchemeSchemeIndex];
            }
        }
        public interface IControlMasterActions
        {
            void OnMouseClickRight(InputAction.CallbackContext context);
            void OnKeyboardSpaceBar(InputAction.CallbackContext context);
            void OnMovement(InputAction.CallbackContext context);
            void OnRightFlipper(InputAction.CallbackContext context);
            void OnLeftFlipper(InputAction.CallbackContext context);
            void OnSpring_Pinball(InputAction.CallbackContext context);
            void OnInvokeBallGotchaAndPinball(InputAction.CallbackContext context);
        }
    }
}
